#!/usr/bin/env python3
"""
Unified TouchDesigner KB MCP Server

Single entrypoint tool that:
- Queries the unified KB (vector + graph) via EnhancedHybridRetrieval
- Generates a TouchDesigner Text DAT python builder script from TDNetworkSpec

This server is intentionally additive: it does not replace existing MCP servers.
"""

from __future__ import annotations

import asyncio
import contextlib
import base64
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Sequence

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

# Ensure UTF-8 output (avoids cp1252 console issues)
os.environ.setdefault("PYTHONIOENCODING", "utf-8")

KB_ROOT = Path(r"C:\TD_Projects\kb_pipeline")
sys.path.insert(0, str(KB_ROOT))

# Add unified_system to path
UNIFIED_SYSTEM_ROOT = Path(r"C:\TD_Projects\unified_system")
sys.path.insert(0, str(UNIFIED_SYSTEM_ROOT))

# Add meta_agentic tooling (compaction) to path
META_AGENTIC_ROOT = Path(r"C:\TD_Projects\META_AGENTIC_TOOL\meta_agentic")
sys.path.insert(0, str(META_AGENTIC_ROOT))

try:
    from hybrid_retrieval_enhanced import EnhancedHybridRetrieval  # type: ignore
except Exception as e:  # pragma: no cover
    raise RuntimeError(f"Failed to import EnhancedHybridRetrieval from {KB_ROOT}: {e}") from e

# Import unified system components (Phase 6 integration)
try:
    from api.network_builder import NetworkBuilder
    from core.format_converter import FormatConverter
    from core.operator_registry import OperatorRegistry
    from validation.pipeline import ValidationPipeline
    from builders.toe_builder import TOEBuilder
except Exception as e:  # pragma: no cover
    raise RuntimeError(f"Failed to import unified_system components from {UNIFIED_SYSTEM_ROOT}: {e}") from e

# Import meta_agentic compaction utilities (optional)
try:  # pragma: no cover
    from compaction import compact_events_to_state, refresh_legacy_yaml
    HAS_COMPACTION = True
    COMPACTION_IMPORT_ERROR = None
except Exception as e:  # pragma: no cover
    HAS_COMPACTION = False
    COMPACTION_IMPORT_ERROR = str(e)

# Import tested ToeBuilderBridge from META_AGENTIC_TOOL (for embed_tox and container support)
META_AGENTIC_TOOL_ROOT = Path(r"C:\TD_Projects\META_AGENTIC_TOOL")
sys.path.insert(0, str(META_AGENTIC_TOOL_ROOT))

try:
    from meta_agentic.execution.toe_builder_bridge import ToeBuilderBridge
    from meta_agentic.execution.tox_builder import ToxBuilder
    HAS_TOE_BUILDER_BRIDGE = True
    TOE_BUILDER_BRIDGE_ERROR = None
except Exception as e:  # pragma: no cover
    HAS_TOE_BUILDER_BRIDGE = False
    TOE_BUILDER_BRIDGE_ERROR = str(e)


def _normalize_sources(value: Any) -> List[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    if isinstance(value, list):
        return [str(v) for v in value]
    return [str(value)]


def _chunk_source(chunk: Dict[str, Any]) -> str:
    meta = chunk.get("meta", {}) or {}
    source = meta.get("source")
    if source:
        return str(source)
    # Infer when missing (some docs chunks may not have source populated)
    if meta.get("operator_type") or meta.get("relpath") or meta.get("has_curator_summary") is not None:
        return "snippets"
    if meta.get("palette_name") or meta.get("palette_category"):
        return "palette"
    return "docs"


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except Exception:
        return default


def _td_create_type(td_type: str) -> str:
    """
    Convert a TD family/type like 'CHOP:noise' to 'noiseCHOP' for parent.create().
    If td_type is already a create type (no ':'), return as-is.
    """
    if ":" not in td_type:
        return td_type
    family, specific = td_type.split(":", 1)
    family = family.strip().upper()
    specific = specific.strip()
    if not specific:
        return td_type
    return f"{specific}{family}"


def build_text_dat_script(
    network: Dict[str, Any],
    target_parent_path: str,
    collision_policy: str = "reuse",
) -> str:
    """
    Generate a TouchDesigner Text DAT Python script to create a network.

    collision_policy:
      - reuse: reuse existing operator if name matches
      - delete: delete existing operator then recreate
    """
    # Accept both "nodes" and "operators" keys (Claude Desktop sends "operators")
    nodes = network.get("nodes", []) or network.get("operators", []) or []
    connections = network.get("connections", []) or []

    lines: List[str] = []
    lines.append("# TouchDesigner Text DAT builder script")
    lines.append("# Generated by Unified TD KB MCP Server")
    lines.append("#")
    lines.append("# How to run:")
    lines.append("# - Paste into a Text DAT")
    lines.append("# - Run the DAT (or call build())")
    lines.append("")
    lines.append("def build(target_parent_path=None):")
    lines.append(f"    parent_path = target_parent_path or {target_parent_path!r}")
    lines.append("    parent = op(parent_path)")
    lines.append("    if parent is None:")
    lines.append("        raise Exception(f'Parent not found: {parent_path}')")
    lines.append("")
    lines.append("    created = {}")
    lines.append("")

    # Create nodes
    lines.append("    # Create/reuse nodes")
    for node in nodes:
        name = node.get("name")
        td_type = node.get("type")
        if not name or not td_type:
            continue
        create_type = _td_create_type(str(td_type))
        lines.append(f"    existing = parent.op({name!r})")
        if collision_policy == "delete":
            lines.append("    if existing is not None:")
            lines.append("        try:")
            lines.append("            existing.destroy()")
            lines.append("        except Exception:")
            lines.append("            pass")
            lines.append("        existing = None")
        lines.append(f"    node = existing or parent.create({create_type!r}, {name!r})")
        lines.append(f"    created[{name!r}] = node")
        lines.append("")

    # Apply parameters
    lines.append("    # Apply parameters")
    for node in nodes:
        name = node.get("name")
        # Accept both "params" and "parameters" keys
        params = node.get("params") or node.get("parameters") or {}
        if not name or not isinstance(params, dict) or not params:
            continue
        lines.append(f"    node = created.get({name!r})")
        lines.append("    if node is None:")
        lines.append("        pass")
        for param_name, param_value in params.items():
            if not isinstance(param_name, str) or not param_name:
                continue
            # Use getattr to avoid syntax issues with invalid parameter names
            lines.append("    try:")
            lines.append(f"        p = getattr(node.par, {param_name!r}, None)")
            lines.append("        if p is not None:")
            lines.append(f"            p.val = {param_value!r}")
            lines.append("    except Exception:")
            lines.append("        pass")
        lines.append("")

    # Apply text content for DAT operators
    lines.append("    # Apply text content for DAT operators")
    for node in nodes:
        name = node.get("name")
        text_content = node.get("text") or node.get("content")
        td_type = str(node.get("type", "")).upper()
        if not name or not text_content:
            continue
        # Only apply text to DAT operators
        if "DAT" in td_type:
            lines.append(f"    node = created.get({name!r})")
            lines.append("    if node is not None:")
            lines.append(f"        node.text = {text_content!r}")
            lines.append("")

    # Wire connections
    lines.append("    # Wire connections")
    for conn in connections:
        from_name = conn.get("from")
        to_name = conn.get("to")
        to_input = conn.get("to_input", 0)
        if not from_name or not to_name:
            continue
        lines.append(f"    src = created.get({str(from_name)!r})")
        lines.append(f"    dst = created.get({str(to_name)!r})")
        lines.append("    if src is None or dst is None:")
        lines.append("        pass")
        lines.append("    else:")
        lines.append(f"        try: dst.setInput({_safe_int(to_input, 0)}, src)")
        lines.append("        except Exception: pass")
        lines.append("")

    lines.append("    return created")
    lines.append("")
    lines.append("build()")
    lines.append("")

    return "\n".join(lines)


with contextlib.redirect_stdout(sys.stderr):
    retrieval = EnhancedHybridRetrieval(enable_cache=True, cache_ttl_hours=24)
    # Initialize unified system components
    registry = OperatorRegistry()
    converter = FormatConverter(registry)
    validator = ValidationPipeline(registry)

app = Server("td-unified-kb-server")


@app.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="td_assistant",
            description=(
                "Unified TouchDesigner assistant tool: query the unified KB (docs/snippets/palette) "
                "and generate TD Text DAT python builder scripts. "
                "\n\nIMPORTANT: Always query BEFORE using unfamiliar operators, especially: "
                "(1) Conversion operators (*to* like soptoCHOP, choptoTOP) - need explicit source params, "
                "(2) Complex operators (audioAnalysis, opticalFlow) - have non-obvious required params, "
                "(3) Any operator you haven't used before - query for snippet examples to see real usage."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "enum": ["query", "batch_query", "build_python", "stats"],
                    },
                    "query": {"type": "string", "description": "Single query string"},
                    "queries": {"type": "array", "items": {"type": "string"}, "description": "Multiple queries for batch_query action"},
                    "n_results": {"type": "integer", "default": 5},
                    "filters": {
                        "type": "object",
                        "properties": {
                            "sources": {
                                "type": "array",
                                "items": {"type": "string", "enum": ["docs", "snippets", "palette"]},
                            }
                            ,
                            "categories": {"type": "array", "items": {"type": "string"}},
                            "difficulty": {"type": "string", "enum": ["beginner", "intermediate", "advanced"]},
                            "min_popularity": {"type": "number", "minimum": 0, "maximum": 1},
                            "tiers": {"type": "array", "items": {"type": "integer", "minimum": 1, "maximum": 4}}
                        },
                    },
                    "network": {"type": "object"},
                    "target_parent_path": {"type": "string", "default": "/project1"},
                    "collision_policy": {"type": "string", "enum": ["reuse", "delete"], "default": "reuse"},
                },
                "required": ["action"],
            },
        ),
        Tool(
            name="td_validate",
            description=(
                "Validate a TouchDesigner network JSON against the unified validation pipeline. "
                "Returns validation report with errors, warnings, and suggestions."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "network": {
                        "type": "object",
                        "description": "TD network JSON (builder, extended, or canonical format)"
                    },
                    "format_layer": {
                        "type": "string",
                        "enum": ["builder", "extended", "canonical"],
                        "default": "builder",
                        "description": "Input format layer"
                    },
                    "verbose": {
                        "type": "boolean",
                        "default": False,
                        "description": "Include detailed validation stages"
                    }
                },
                "required": ["network"]
            }
        ),
        Tool(
            name="td_convert",
            description=(
                "Convert TouchDesigner network JSON between format layers. "
                "Supports: builder (AI-friendly) ↔ extended (ground truth) ↔ canonical (compact)."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "network": {
                        "type": "object",
                        "description": "TD network JSON to convert"
                    },
                    "source_layer": {
                        "type": "string",
                        "enum": ["builder", "extended", "canonical"],
                        "description": "Source format layer"
                    },
                    "target_layer": {
                        "type": "string",
                        "enum": ["builder", "extended", "canonical"],
                        "description": "Target format layer"
                    }
                },
                "required": ["network", "source_layer", "target_layer"]
            }
        ),
        Tool(
            name="td_build_network",
            description=(
                "Build a TouchDesigner .toe or .tox file from network JSON. "
                "Supports two input formats: (1) 'network' for simple builder format, "
                "(2) 'network_design' for advanced features including containers, embed_tox for palette components, "
                "and hierarchical connections. Creates .toe.dir directory and runs toecollapse to create final .toe. "
                "\n\nCRITICAL: Conversion operators (soptoCHOP, choptoTOP, datToCHOP, topToCHOP, etc.) "
                "require EXPLICIT source parameters - wire connections alone do NOT configure them. "
                "Before using any *to* conversion operator, query td_assistant for the operator snippet "
                "to learn required parameters. Example: soptoCHOP needs 'sop' param, choptoTOP needs 'chop' param."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "network": {
                        "type": "object",
                        "description": "TD network JSON (builder format) - simple operators and connections"
                    },
                    "network_design": {
                        "type": "object",
                        "description": "Advanced network design with containers, embed_tox support for palette components, and hierarchical paths"
                    },
                    "output_path": {
                        "type": "string",
                        "description": "Output file path (e.g., 'C:/TD_Projects/builds/project.toe')"
                    },
                    "mode": {
                        "type": "string",
                        "enum": ["toe", "tox"],
                        "default": "toe",
                        "description": "Build mode: toe (project) or tox (component)"
                    },
                    "verbose": {
                        "type": "boolean",
                        "default": False,
                        "description": "Print build progress"
                    }
                },
                "required": ["output_path"]
            }
        ),
        Tool(
            name="td_compact_expertise",
            description=(
                "Compact meta-agentic expertise event log into expertise_state.yaml and optionally refresh legacy YAML "
                "views. Uses append-only JSONL -> YAML compaction per INTEROP_AND_POLICY.md."
            ),
            inputSchema={
                "type": "object",
                "properties": {
                    "refresh_yaml": {"type": "boolean", "default": True},
                    "events_path": {"type": "string", "description": "Optional override for events JSONL path"},
                    "state_path": {"type": "string", "description": "Optional override for state YAML path"}
                }
            }
        )
    ]


@app.call_tool()
async def call_tool(name: str, arguments: dict) -> Sequence[TextContent]:
    # Phase 6: New tools - td_validate, td_convert, td_build_network
    if name == "td_validate":
        try:
            network_json = arguments.get("network")
            if not network_json:
                return [TextContent(type="text", text="Error: 'network' is required")]

            format_layer = arguments.get("format_layer", "builder")
            verbose = arguments.get("verbose", False)

            # Convert to TDNetwork if needed
            if format_layer == "builder":
                network = converter.from_builder(network_json)
            elif format_layer == "canonical":
                network = converter.from_canonical(network_json)
            else:  # extended
                # TODO: Implement proper Extended JSON deserialization
                # For now, use builder format
                network = converter.from_builder(network_json)

            # Validate
            project_name = network_json.get("meta", {}).get("project_name", "network")
            report = validator.validate(network, project_name)

            # Build response
            result = {
                "valid": report.valid,
                "total_errors": report.total_errors,
                "total_warnings": report.total_warnings,
                "errors": [{"stage": e.stage, "message": e.message, "severity": e.severity}
                          for e in report.get_errors()],
                "warnings": [{"stage": w.stage, "message": w.message, "severity": w.severity}
                            for w in report.get_warnings()]
            }

            if verbose:
                # Build stages from report.stages list
                result["stages"] = {}
                for stage_report in report.stages:
                    result["stages"][stage_report.stage] = {
                        "passed": stage_report.status == "PASS",
                        "errors": len(stage_report.errors),
                        "warnings": len(stage_report.warnings)
                    }

            return [TextContent(type="text", text=json.dumps(result, indent=2))]
        except Exception as e:
            return [TextContent(type="text", text=f"Error validating network: {str(e)}")]

    elif name == "td_convert":
        try:
            network_json = arguments.get("network")
            if not network_json:
                return [TextContent(type="text", text="Error: 'network' is required")]

            source_layer = arguments.get("source_layer")
            target_layer = arguments.get("target_layer")

            if not source_layer or not target_layer:
                return [TextContent(type="text", text="Error: 'source_layer' and 'target_layer' are required")]

            # Convert source → Extended (ground truth)
            if source_layer == "builder":
                network = converter.from_builder(network_json)
            elif source_layer == "canonical":
                network = converter.from_canonical(network_json)
            else:  # already extended
                # TODO: Proper Extended deserialization
                network = converter.from_builder(network_json)

            # Convert Extended → target
            if target_layer == "builder":
                result_json = converter.to_builder(network)
            elif target_layer == "canonical":
                result_json = converter.to_canonical(network)
            else:  # extended
                # Return extended format (serialize TDNetwork to builder and back)
                # This preserves structure while giving a JSON-serializable dict
                result_json = converter.to_builder(network)
                result_json["format_layer"] = "extended"

            return [TextContent(type="text", text=json.dumps(result_json, indent=2))]
        except Exception as e:
            return [TextContent(type="text", text=f"Error converting network: {str(e)}")]

    elif name == "td_build_network":
        try:
            network_design = arguments.get("network_design")
            network_json = arguments.get("network")

            output_path = arguments.get("output_path")
            if not output_path:
                return [TextContent(type="text", text="Error: 'output_path' is required")]

            mode = arguments.get("mode", "toe")
            verbose = arguments.get("verbose", False)

            # Normalize path - if Linux-style path, redirect to Windows builds dir
            # Claude Desktop runs in Linux sandbox but MCP server is on Windows
            if output_path.startswith('/') or ':' not in output_path:
                # Extract just the filename and use Windows builds directory
                filename = Path(output_path).name
                output_path = f"C:/TD_Projects/builds/{filename}"

            # Ensure output directory exists
            output = Path(output_path)
            output.parent.mkdir(parents=True, exist_ok=True)

            # Check if using new network_design format with ToeBuilderBridge
            if network_design and HAS_TOE_BUILDER_BRIDGE:
                # Use tested ToeBuilderBridge with embed_tox support
                try:
                    if mode == "tox":
                        bridge = ToxBuilder(output.parent)
                        result_path = bridge.build_tox(network_design, output.stem)
                    else:
                        bridge = ToeBuilderBridge(output.parent)
                        result_path = bridge.build_from_design(network_design, output.stem)

                    # Count operators and connections (BUG-I FIX: include container connections)
                    op_count = 0
                    conn_count = len(network_design.get("connections", []))
                    for container in network_design.get("containers", []):
                        op_count += len(container.get("operators", []))
                        # Count container-internal connections (flat or nested format)
                        conn_count += len(container.get("connections", []))
                        network = container.get("network", {})
                        conn_count += len(network.get("connections", []))
                    op_count += len(network_design.get("operators", []))

                    # Check if file was actually created
                    if result_path is None or not Path(result_path).exists():
                        return [TextContent(type="text", text=json.dumps({
                            "success": False,
                            "builder": "ToeBuilderBridge",
                            "error": "Build completed but file was not created",
                            "attempted_path": str(result_path) if result_path else "None"
                        }, indent=2))]

                    # Read file and encode as base64 for transfer
                    file_data = None
                    file_size = Path(result_path).stat().st_size
                    if file_size < 10 * 1024 * 1024:  # Only transfer files under 10MB
                        with open(result_path, 'rb') as f:
                            file_data = base64.b64encode(f.read()).decode('utf-8')

                    result = {
                        "success": True,
                        "builder": "ToeBuilderBridge",
                        "output_file": str(result_path),
                        "file_size": file_size,
                        "operators": op_count,
                        "connections": conn_count,
                        "features_used": {
                            "containers": len(network_design.get("containers", [])) > 0,
                            "embed_tox": any(
                                op.get("embed_tox")
                                for container in network_design.get("containers", [])
                                for op in container.get("operators", [])
                            )
                        }
                    }

                    # Include file data if available
                    if file_data:
                        result["file_base64"] = file_data
                        result["transfer_note"] = "File included as base64. Decode and save to use."

                    return [TextContent(type="text", text=json.dumps(result, indent=2))]
                except Exception as e:
                    import traceback
                    return [TextContent(type="text", text=json.dumps({
                        "success": False,
                        "builder": "ToeBuilderBridge",
                        "error": str(e),
                        "traceback": traceback.format_exc()
                    }, indent=2))]

            elif network_design and not HAS_TOE_BUILDER_BRIDGE:
                return [TextContent(type="text", text=json.dumps({
                    "success": False,
                    "error": "network_design format requires ToeBuilderBridge which failed to import",
                    "import_error": TOE_BUILDER_BRIDGE_ERROR
                }, indent=2))]

            elif not network_json:
                return [TextContent(type="text", text="Error: either 'network' or 'network_design' is required")]

            # Convert network format to network_design and use ToeBuilderBridge
            # This handles: operators/nodes, parameters/params, combined types like noiseCHOP
            if HAS_TOE_BUILDER_BRIDGE:
                try:
                    # Convert network to network_design format
                    converted_design = {
                        "project": network_json.get("meta", {}).get("project_name", output.stem),
                        "operators": [],
                        "connections": network_json.get("connections", [])
                    }

                    # Handle both "operators" and "nodes" keys
                    ops = network_json.get("operators", []) or network_json.get("nodes", [])
                    for op in ops:
                        converted_op = {
                            "name": op.get("name", ""),
                            "type": op.get("type", ""),
                        }
                        # Handle both "parameters" and "params" keys
                        params = op.get("parameters", {}) or op.get("params", {})
                        if params:
                            converted_op["parameters"] = params
                        converted_design["operators"].append(converted_op)

                    # Use ToeBuilderBridge
                    if mode == "tox":
                        bridge = ToxBuilder(output.parent)
                        result_path = bridge.build_tox(converted_design, output.stem)
                    else:
                        bridge = ToeBuilderBridge(output.parent)
                        result_path = bridge.build_from_design(converted_design, output.stem)

                    # Check if file was actually created
                    if result_path is None or not Path(result_path).exists():
                        return [TextContent(type="text", text=json.dumps({
                            "success": False,
                            "builder": "ToeBuilderBridge",
                            "error": "Build completed but file was not created",
                            "attempted_path": str(result_path) if result_path else "None",
                            "converted_from": "network"
                        }, indent=2))]

                    # Return local file path directly (MCP runs locally, no need for base64)
                    file_size = Path(result_path).stat().st_size

                    # Verify file is valid (should be at least 500 bytes for a minimal .tox)
                    if file_size < 500:
                        return [TextContent(type="text", text=json.dumps({
                            "success": False,
                            "builder": "ToeBuilderBridge",
                            "error": f"Generated file too small ({file_size} bytes) - toecollapse may have failed",
                            "output_file": str(result_path),
                            "toc_file": str(result_path).replace('.tox', '.tox.toc').replace('.toe', '.toe.toc'),
                            "dir": str(result_path) + ".dir",
                            "hint": "Check if toecollapse.exe is available and working"
                        }, indent=2))]

                    result = {
                        "success": True,
                        "builder": "ToeBuilderBridge",
                        "output_file": str(result_path),
                        "file_size": file_size,
                        "operators": len(converted_design.get("operators", [])),
                        "connections": len(converted_design.get("connections", [])),
                        "converted_from": "network",
                        "note": "File created locally. Open directly in TouchDesigner."
                    }

                    return [TextContent(type="text", text=json.dumps(result, indent=2))]
                except Exception as e:
                    import traceback
                    return [TextContent(type="text", text=json.dumps({
                        "success": False,
                        "builder": "ToeBuilderBridge",
                        "error": str(e),
                        "traceback": traceback.format_exc()
                    }, indent=2))]

            # Fall back to original NetworkBuilder if ToeBuilderBridge unavailable
            meta = network_json.get("meta", {})
            project_name = meta.get("project_name", "network")

            builder = NetworkBuilder(project_name, mode=mode)

            # Add operators - handle both "operators" and "nodes" keys
            nodes = network_json.get("operators", []) or network_json.get("nodes", [])
            for node in nodes:
                node_path = node.get("path", "")
                name = node_path.split("/")[-1] if node_path else node.get("name", "")

                # Parse type - handle combined format like "noiseCHOP"
                op_type = node.get("type", "")
                family = node.get("family", "")
                if not family and op_type:
                    # Try to extract family from combined type (e.g., "noiseCHOP" -> "CHOP", "noise")
                    for fam in ["CHOP", "TOP", "SOP", "DAT", "COMP", "MAT", "POP"]:
                        if op_type.upper().endswith(fam):
                            family = fam
                            op_type = op_type[:-len(fam)]
                            break

                if not name or not family or not op_type:
                    continue

                # Determine parent
                parent = None
                if "/" in node_path:
                    parent = "/".join(node_path.split("/")[:-1])

                builder.add_operator(name, family, op_type, parent=parent)

                # Set parameters - handle both "parameters" and "params" keys
                params = node.get("parameters", {}) or node.get("params", {})
                for param_name, param_value in params.items():
                    try:
                        builder.set_parameter(name, param_name, param_value)
                    except Exception:
                        pass  # Skip invalid parameters

                # Set text content for DAT operators (Table DAT, Text DAT, Script DAT)
                text_content = node.get("text") or node.get("content")
                if text_content and family == "DAT":
                    try:
                        builder.set_text(name, text_content)
                    except Exception:
                        pass  # Skip if set_text fails

            # Add connections
            connections = network_json.get("connections", [])
            for conn in connections:
                from_name = conn.get("from", "")
                to_name = conn.get("to", "")
                to_input = conn.get("to_input", 0)

                if from_name and to_name:
                    try:
                        builder.connect(from_name, to_name, target_input=to_input)
                    except Exception:
                        pass  # Skip invalid connections

            # Validate
            if not builder.is_valid():
                report = builder.validate()
                errors = [e.message for e in report.get_errors()]
                return [TextContent(type="text", text=json.dumps({
                    "success": False,
                    "error": "Network validation failed",
                    "errors": errors[:5]
                }, indent=2))]

            # Build
            if mode == "toe":
                toc_file = builder.build_toe(output, verbose=verbose)
            else:
                toc_file = builder.build_tox(output, verbose=verbose)

            result = {
                "success": True,
                "builder": "NetworkBuilder",
                "toc_file": str(toc_file),
                "dir": str(toc_file).replace(".toc", ".dir"),
                "operators": len(builder),
                "connections": len(builder.connections),
                "next_step": f"toecollapse {toc_file}"
            }

            return [TextContent(type="text", text=json.dumps(result, indent=2))]
        except Exception as e:
            import traceback
            return [TextContent(type="text", text=json.dumps({
                "success": False,
                "error": str(e),
                "traceback": traceback.format_exc()
            }, indent=2))]

    elif name == "td_compact_expertise":
        if not HAS_COMPACTION:
            return [TextContent(type="text", text=json.dumps({
                "success": False,
                "error": "Compaction utilities unavailable",
                "details": COMPACTION_IMPORT_ERROR
            }, indent=2))]

        try:
            refresh_yaml = bool(arguments.get("refresh_yaml", True))
            events_path_arg = arguments.get("events_path")
            state_path_arg = arguments.get("state_path")

            from pathlib import Path as CompPath
            events_path = CompPath(events_path_arg) if events_path_arg else None
            state_path = CompPath(state_path_arg) if state_path_arg else None

            success, msg = compact_events_to_state(events_path=events_path, state_path=state_path)
            result = {
                "success": success,
                "compaction": msg
            }

            if refresh_yaml:
                refresh_success, refresh_msg = refresh_legacy_yaml(state_path=state_path)
                result["refresh_success"] = refresh_success
                result["refresh"] = refresh_msg

            return [TextContent(type="text", text=json.dumps(result, indent=2))]
        except Exception as e:
            import traceback
            return [TextContent(type="text", text=json.dumps({
                "success": False,
                "error": str(e),
                "traceback": traceback.format_exc()
            }, indent=2))]

    # Original td_assistant tool
    elif name == "td_assistant":
        action = arguments.get("action")

        if action == "stats":
            return [TextContent(type="text", text=json.dumps(retrieval.get_performance_stats(), indent=2))]

        if action == "build_python":
            network = arguments.get("network") or {}
            target_parent_path = arguments.get("target_parent_path") or "/project1"
            collision_policy = arguments.get("collision_policy") or "reuse"
            script = build_text_dat_script(network, target_parent_path, collision_policy=collision_policy)
            result = {"target_parent_path": target_parent_path, "script": script}
            return [TextContent(type="text", text=json.dumps(result, indent=2))]

        if action == "query":
            query = arguments.get("query")
            if not isinstance(query, str) or not query.strip():
                return [TextContent(type="text", text="Error: 'query' must be a non-empty string")]

            n_results = int(arguments.get("n_results", 5) or 5)
            filters = arguments.get("filters") or {}
            allowed_sources = set(_normalize_sources(filters.get("sources")))
            categories = set(_normalize_sources(filters.get("categories")))
            difficulty = filters.get("difficulty")
            min_popularity = filters.get("min_popularity")
            tiers = set(filters.get("tiers") or [])

            def passes_filters(chunk: Dict[str, Any]) -> bool:
                meta = chunk.get("meta", {}) or {}
                source = _chunk_source(chunk)
                if allowed_sources and source not in allowed_sources:
                    return False
                if difficulty and meta.get("difficulty_level") and meta.get("difficulty_level") != difficulty:
                    return False
                if min_popularity is not None:
                    try:
                        if float(meta.get("popularity_score", 0)) < float(min_popularity):
                            return False
                    except Exception:
                        return False
                if tiers:
                    try:
                        if int(meta.get("tier")) not in {int(t) for t in tiers}:
                            return False
                    except Exception:
                        return False
                if categories:
                    chunk_cats = meta.get("use_case_categories") or []
                    if isinstance(chunk_cats, str):
                        chunk_cats = [chunk_cats]
                    if not set([str(c) for c in chunk_cats]).intersection(categories):
                        return False
                return True

            # Overfetch then filter (retrieval itself is unfiltered)
            # Use async version for better performance
            raw = await retrieval.hybrid_search_async(query, n_results=max(25, n_results * 5))

            results: List[Dict[str, Any]] = []
            for chunk, score in raw:
                if not passes_filters(chunk):
                    continue
                source = _chunk_source(chunk)
                results.append(
                    {
                        "score": score,
                        "source": source,
                        "text": chunk.get("text", ""),
                        "meta": chunk.get("meta", {}),
                        "chunk_type": chunk.get("chunk_type"),
                    }
                )
                if len(results) >= n_results:
                    break

            payload = {
                "query": query,
                "n_results": n_results,
                "filters": {
                    **({"sources": sorted(list(allowed_sources))} if allowed_sources else {}),
                    **({"categories": sorted(list(categories))} if categories else {}),
                    **({"difficulty": difficulty} if difficulty else {}),
                    **({"min_popularity": min_popularity} if min_popularity is not None else {}),
                    **({"tiers": sorted(list(tiers))} if tiers else {}),
                },
                "results": results,
            }
            return [TextContent(type="text", text=json.dumps(payload, indent=2))]

        if action == "batch_query":
            # Run multiple queries in parallel for efficiency
            queries = arguments.get("queries", [])
            if not queries:
                return [TextContent(type="text", text=json.dumps({"error": "No queries provided"}))]

            n_results = int(arguments.get("n_results", 3))  # Fewer per query in batch mode

            async def run_query(q: str):
                try:
                    raw = await retrieval.hybrid_search_async(q, n_results=n_results * 3)
                    results = []
                    for chunk, score in raw[:n_results]:
                        results.append({
                            "score": score,
                            "source": _chunk_source(chunk),
                            "text": chunk.get("text", "")[:500],  # Truncate for batch
                            "meta": chunk.get("meta", {}),
                        })
                    return {"query": q, "results": results}
                except Exception as e:
                    return {"query": q, "error": str(e)}

            # Run all queries in parallel
            import asyncio
            batch_results = await asyncio.gather(*[run_query(q) for q in queries])

            return [TextContent(type="text", text=json.dumps({
                "batch_count": len(queries),
                "results": batch_results
            }, indent=2))]

        return [TextContent(type="text", text=f"Error: unknown action '{action}'")]

    # Unknown tool
    return [TextContent(type="text", text=f"Error: unknown tool '{name}'")]


async def main() -> None:
    async with stdio_server() as (read_stream, write_stream):
        await app.run(read_stream, write_stream, app.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
